### ISSUE TITLE
data_preprocessing

### ISSUE THREAD

**Issue by bridgeqiqi** [gdwang08/Jigsaw-VAD#1]
Hi, thanks a lot for your great work. I'm trying to reproduce this work following your released code. It seems that you've preprocessed the data into the .npy format with the size (3,7,64,64). The raw data frames from those three datasets are saved as .bmp/.jpg format extracted from the .mp4 video data. So how did you do that to transform the data into the .npy format with the size (3,7,64,64)? Could you please share the data_preprocessing code? Thanks.

**Comment by gdwang08** [comment]
I suggest that you use the detection results (detect/**.pkl) to offline generate the testing/training cubes for the three datasets.

**Comment by bridgeqiqi** [comment]
Thanks a lot for your response.

**Comment by chaoqinhuang** [comment]
Hi @gdwang08, thank you for your great work! Could you please share the code for using the detection results to generate the npy format data? Thanks.

**Comment by gdwang08** [comment]
@chaoqinhuang, I have updated the script for patch generation as well as the meta info for the datasets. Please check!

**Comment by chaoqinhuang** [comment]
Thank you very much!
