### ISSUE TITLE
about ****_yolov3.pkl

### ISSUE THREAD

**Issue by Smallwhite999** [gdwang08/Jigsaw-VAD#11]
Hello, thanks a lot for your great work. I would like to know how to generate shanghaitech_train_detect_result_yolov3.pkl？ Or is there a code for generating .pkl for reference?

**Comment by gdwang08** [comment]
@Smallwhite999 You may refer to https://github.com/wizyoung/YOLOv3_TensorFlow to generate the detection results by yourself.

**Comment by Smallwhite999** [comment]
> @Smallwhite999 You may refer to https://github.com/wizyoung/YOLOv3_TensorFlow to generate the detection results by yourself.

could you please clarify whether these .pkl files contain trained models based on the UCSD or ShanghaiTech datasets, or if they store object information from these respective datasets? In other words, what type of information is stored within the .pkl files?

**Comment by Smallwhite999** [comment]
> @Smallwhite999 You may refer to https://github.com/wizyoung/YOLOv3_TensorFlow to generate the detection results by yourself.

@gdwang08 
I'm sorry for bothering you again. could you please clarify whether these .pkl files contain trained models based on the UCSD or ShanghaiTech datasets, or if they store object information from these respective datasets? In other words, what type of information is stored within the .pkl files?
