### ISSUE TITLE
generate the shanghaitech_test_detect_result_yolov3.pkl

### ISSUE THREAD

**Issue by yoghurtea** [gdwang08/Jigsaw-VAD#12]
Hello, if possible, can you tell me the process of generating the pkl file in more detail, or is there any relevant code?
Thank you so much.

**Comment by gdwang08** [comment]
You may refer to https://github.com/gdwang08/Jigsaw-VAD/issues/11#issuecomment-1545248060. Following [SSMTL](https://arxiv.org/abs/2011.07491), we set the confidence score 0.8 for STC and Avenue, and 0.5 for UCSD Ped2.

**Comment by yoghurtea** [comment]
Thanks a lot, I will have a try.
