### ISSUE TITLE
Dataset file structure and details

### ISSUE THREAD

**Issue by ZhangHuixin1103** [gdwang08/Jigsaw-VAD#13]
Howdy!

Thanks for your great work!

I wish to get the full file structure in /irip/wangguodong_2020/projects/datasets/vad/.

What your code (dataset part) indicates seems to be slightly different from the original datasets, so I'm curious about the modifications you did to the datasets.

(I actually saw your avenue.zip in another issue. Would you mind sharing more?  ^^ )

**Comment by gdwang08** [comment]
the dataset structure as follows:

vad/
--avenue/
----avenue.mat
----testing/
----01/
------0000.jpg
------1438.jpg
----21/
----training/
------01/
--------0000.jpg
--------1363.jpg
------16

--ped2/
----ped2.mat
----testing/
------01/
------000.jpg
------179.jpg
------12/
----training/
------01/
------16/

--shanghaitech/
----testing/
------01_0014/
--------000.jpg
--------264.jpg
------01_0015/
----training/
------01_001/
--------000000.jpg
--------000001.jpg
------13_007
----frame_masks/
------01_0014.npy
------12_0175.npy
----pixel_masks/
------01_0014.npy
------12_0175.npy

**Comment by ZhangHuixin1103** [comment]
Thanks !
