### ISSUE TITLE
Sample Step for ShanghaiTech?

### ISSUE THREAD

**Issue by ganqieniurou** [gdwang08/Jigsaw-VAD#3]
Thanks a lot for the great work.
I noticed that the sample step for the training set of STC is set to be 5. Is that means only 3 frames out of 9 (i.e. NO.1, 5, 9) are used for training?

**Comment by gdwang08** [comment]
@ganqieniurou We use consecutive 9 frames for both training and testing for STC. We set the sample step be 5 for STC only for saving the hard drive space. In other words, we pick up cubes at intervals of 5 frames, otherwise it takes up ~600GB.

**Comment by ganqieniurou** [comment]
thank you so much for the really quick reply
really appreciate it
