### ISSUE TITLE
about two remake_video_output function

### ISSUE THREAD

**Issue by XubeiPan666** [gdwang08/Jigsaw-VAD#5]
Thanks for your great work! I have a question about why using the function remake_ video_ 3d_ output in dataset ped2 and avenue instead of the function remake_ video_ output using in dataset shanghaitech? I'm looking forward to your reply！

**Comment by gdwang08** [comment]
@xusuger We follow [AED-SSMTL](https://github.com/lilygeorgescu/AED-SSMTL) and do not use the 3D filter for STC while we actually find no large differences when using it.

**Comment by XubeiPan666** [comment]
> 



> @xusuger We follow [AED-SSMTL](https://github.com/lilygeorgescu/AED-SSMTL) and do not use the 3D filter for STC while we actually find no large differences when using it.

Ok，thanks for your reply very much!
