### ISSUE TITLE
According to evaluate.py

### ISSUE THREAD

**Issue by 20220201yyds** [gdwang08/Jigsaw-VAD#6]
Thanks for your performance and I have learn your code for a week. May I ask where can I find the label_test file in SHANGHAITECH_LABEL_PATH of GroundTruthLoader? I am glad if you can reply my questions.

**Comment by gdwang08** [comment]
You could download it from [here](http://101.32.75.151:8181/dataset/shanghaitech.tar.gz).

**Comment by 20220201yyds** [comment]
Is the test_frame_mask file or test_pixel_file

**Comment by gdwang08** [comment]
test_frame_mask

**Comment by 20220201yyds** [comment]
thanks a lot

**Comment by 20220201yyds** [comment]
Thank you a lot
