### ISSUE TITLE
KeyError: 'frames'

### ISSUE THREAD

**Issue by banzhuan37** [gdwang08/Jigsaw-VAD#8]
hi,

Thanks for your brilliant work. When I tried to run gen_patches.py, the error appeared.
"
Traceback (most recent call last):
  File "gen_patches.py", line 185, in <module>
    frame_num=args.sample_num)
  File "gen_patches.py", line 63, in __init__
    self._load_data(file_list)
  File "gen_patches.py", line 78, in _load_data
    detect_result = self.detect[video_file][frame]
KeyError: 'frames'

"
I did not find variable frames in gen_patches.py. How could I solve this problem.
Many thanks

**Comment by banzhuan37** [comment]
"
print_interval 20 --batch_size 192 --sample_num 9 --epochs 100 --static_threshold 0.2
The running_data : 2022-11-05-22-37-29
-------------val_step : 100
-------------print_interval : 20
-------------epochs : 100
-------------gpu_id : 0
-------------log_date : None
-------------batch_size : 192
-------------static_threshold : 0.2
-------------sample_num : 9
-------------filter_ratio : 0.8
-------------checkpoint : None
-------------dataset : shanghaitech
-------------device : cuda:0
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    train(args)
  File "main.py", line 64, in train
    static_threshold=args.static_threshold)
  File "/home/vad/Jigsaw-VAD-main/Jigsaw-VAD-main/dataset.py", line 63, in __init__
    self._load_data(file_list)
  File "/home/vad/Jigsaw-VAD-main/Jigsaw-VAD-main/dataset.py", line 80, in _load_data
    detect_result = self.detect[video_file][frame]
KeyError: 'videos'

"

Also when I try to run main.py first, the error appears with "videos"

**Comment by gdwang08** [comment]
@banzhuan37 I have no ideas what is going on with the two errors neither but I suggest you could validate the paths of .jpg and generated .npy before running gen_patches.py and main.py, respectively. You may refer to https://github.com/gdwang08/Jigsaw-VAD/issues/2 for the data preparation.

**Comment by banzhuan37** [comment]
Thank you for your swift response, I have adjusted the dataset structure as you guided and it worked.
But I am running into another error when I run main.py
"
Original Traceback (most recent call last):
  File "/home/.conda/envs/mmaction2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/.conda/envs/mmaction2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/.conda/envs/mmaction2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vad/Jigsaw-VAD-main/Jigsaw-VAD-main/dataset.py", line 123, in __getitem__
    obj = self.get_object(record["video_name"], record["frame"], record["object"])
  File "/home/vad/Jigsaw-VAD-main/Jigsaw-VAD-main/dataset.py", line 152, in get_object
    obj = np.load(os.path.join(video_dir, str(frame) + '_' + str(obj_id) + '.npy'))   # (3, 7, 64, 64)
  File "/home/.conda/envs/mmaction2/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'shanghaitech/training/01_058/93_1.npy'
"
It appears that in the file dataset.py line152 , which requires fetching training npy files, but we only generate test npy files in gen_patches.py file. So , in my understanding, during training time, the object patches are generated online and stored somewhere but not in the address that line 151 mentioned. Can you help me fix this bug, thank you very much.

**Comment by banzhuan37** [comment]
@gdwang08  I also tried to generate npy files for training set but when I run main.py, a new error appears  "IndexError: list index out of range"

**Comment by banzhuan37** [comment]
I have solved this problem by reorganizing the data structure.

**Comment by Smallwhite999** [comment]
> @gdwang08 I also tried to generate npy files for training set but when I run main.py, a new error appears "IndexError: list index out of range"

@banzhuan37 I also encountered the same problem. How did you solve it?

**Comment by Smallwhite999** [comment]
> I have solved this problem by reorganizing the data structure.

I also had the same problem with the ped2 data set. When I reorganized the data structure, I still had the same problem. How did you handle it

**Comment by Smallwhite999** [comment]
> I have solved this problem by reorganizing the data structure.
@banzhuan37 
I also had the same problem with the ped2 data set. When I reorganized the data structure, I still had the same problem. How did you handle it
